### ISSUE TITLE
Revisar permissão das views do fale conosco

### ISSUE THREAD

**Issue by brunobbbs** [govbr/mpdg-govbr-faleconosco#10]
Olá pessoal,

Pude observar que existem várias views que deveriam ser acessadas possivelmente apenas pelo admin do fale conosco, no entanto essas views estão abertas para o público. Alguns exemplos:

* https://www.governoeletronico.gov.br/@@usuarios
* https://www.governoeletronico.gov.br/@@textos-prontos
* https://www.governoeletronico.gov.br/@@mensagens-arquivadas-admin
* https://www.governoeletronico.gov.br/@@inserir-faq
* https://www.governoeletronico.gov.br/@@fale-conosco-charts
* https://www.governoeletronico.gov.br/@@categoria-charts-view

Além das views acima, as views abaixo também estão sem controle de permissão, mas não visualizei nenhum retorno quando acessadas externamente:

* `MensagensView` (/@@mensagens): não exibe nenhum conteúdo na página.
* `MensagemAddView` (/@@add-mensagem): acessando de fora recebo erro 503.

**Comment by brunobbbs** [comment]
Para a maioria dessas views, se não todas, basta que a view herde da classe `FaleConoscoAdminRequired`

ex.:
```
from mpdg.govbr.faleconosco.browser.utilities import FaleConoscoAdminRequired


class UsuariosView(FaleConoscoAdminRequired, grok.View):
    """ View para adicionar usuarios ao encaminhar
    """
```

Se a view tiver implementado o método `update()` temos também que chamar o `super()`. Ex.:

```
def update(self, **kwargs):
    super().update(**kwargs)
    ...
```

**Comment by samuel-morais** [comment]
Corrigido.
